---
- name: Make sure the minio binary exists
  ansible.builtin.stat:
    path: "{{ install_path }}/minio"
  register: minio_binary

- name: Move minio binary from localhost to target servers
  ansible.builtin.copy:
    src: "/home/lyon/w/minio"
    dest: "{{ install_path }}/minio"
    mode: "0755"
  when: not minio_binary.stat.exists

- name: Ensure that /data path exists
  ansible.builtin.stat:
    path: /data
  register: data

- name: Create /data dir
  ansible.builtin.file:
    path: /data
    state: directory
  become: true
  when: not data.stat.exists

- name: Ensure that storage_path exists
  ansible.builtin.stat:
    path: "{{ storage_path }}"

- name: Format The storage path with xfs
  ansible.builtin.filesystem:
    fstype: xfs
    dev: "{{ storage_path }}"
    state: present

- name: Update /etc/fstab to persist mount path
  ansible.builtin.mount:
    path: /data
    src: "{{ storage_path }}"
    fstype: xfs
    opts: defaults,noatime,nofail
    dump: 0
    passno: 0
    state: present

- name: Mount all filesystems
  ansible.builtin.shell: mount -a

- name: Add custom hosts entries
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['minio'] %}
      {{ hostvars[host].ansible_host }} {{ host }}
      {% endfor %}
    marker: "# {mark} Minio hosts"
    create: no

- name: Move minio's default template to /etc/default/
  ansible.builtin.template:
    src: minio.j2
    dest: /etc/default/minio
  notify: restart minio

- name: Move minio unit file to /lib/systemd/system/
  ansible.builtin.template:
    src: minio.service.j2
    dest: /lib/systemd/system/minio.service
  notify: reload and restart minio systemd




