---
- name: Make sure the installation path exists
  ansible.builtin.file:
    path: "{{ install_path }}"
    mode: '0755'
    recurse: yes
    state: directory
  become: true
  register: minio_binary

- name: Download minio binary
  ansible.builtin.get_url:
    url: "{{ bin_url }}"
    dest: "{{ install_path }}/minio"
    mode: '0755'
  notify: restart minio
  when: not minio_binary

- name: Ensure /data directory exists
  ansible.builtin.file:
    path: /data
    state: directory
  become: true

- name: Format The storage path with xfs
  ansible.builtin.filesystem:
    fstype: xfs
    dev: "{{ storage_path }}"

- name: Update /etc/fstab to persist mount path
  ansible.builtin.mount:
    path: /data
    src: "{{ storage_path }}"
    fstype: xfs
    opts: defaults,noatime,nofail
    dump: 0
    passno: 0
    state: present

- name: Mount all filesystems
  ansible.builtin.shell: mount -a

- name: Add custom hosts entries
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['minio'] %}
      {{ hostvars[host].ansible_host }} {{ host }}
      {% endfor %}
    marker: "# {mark} Minio hosts"
    create: no

- name: Move minio's default template to /etc/default/
  ansible.builtin.template:
    src: minio.j2
    dest: /etc/default/minio
  notify: restart minio

- name: Move minio unit file to /lib/systemd/system/
  ansible.builtin.template:
    src: minio.service.j2
    dest: /lib/systemd/system/minio.service
  notify: restart minio

- name: Start minio service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name : 'minio'
  become: true


