---
- name: reload and restart minio systemd
  ansible.builtin.systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name : 'minio'
  become: true

- name: restart minio
  ansible.builtin.systemd:
    state: restarted
    name : 'minio'
  become: true
